Update SumTotal.md
MicrosoftDocs/powerquery-docs pull request #161
Opened 2021-08-19 13:22 UTC by Gareth-Rodrigues

updating SumTotal .md file with image for visual instruction of Sumtotal Connector from within PowerBI Desktop
added note for mention of scripts popup warning during OAuth login

2021-08-25 16:49 UTC, bezhan-msft commented on powerquery-docs/Connectors/SumTotal.md
> +| Products | Power BI (Datasets)<br/>Power BI (Dataflows)<br/>Dynamics 365 Customer Insights |
This is not accurate - the connector is and only will be able in Power BI (Datasets) for the foreseeable future.

2021-08-25 16:49 UTC, bezhan-msft commented on powerquery-docs/Connectors/SumTotal.md
> +| Function Reference Documentation | Web.Conents <br> Table.ToNavigationTable <br>Table.FromRecords <br> Json.Document|
If this is changed, this should include links to the M function reference for each of these functions

2021-08-25 16:49 UTC, bezhan-msft commented on powerquery-docs/Connectors/SumTotal.md
> +## Finding your Sumtotal Hosted URL
nit/style - should remain "hosted"

2021-10-06 12:14 UTC, Gareth-Rodrigues commented
Hello Bob,

 

Sure thing I will take a look and amend where necessary.

Thanks

 

Kind regards 

Gareth Rodrigues | Software Engineer

COMPRSA | Cloud-based Business Solutions

 ***@***.***> ***@***.***|  <http://www.comprsa.com/> comprsa.com

RSA: +2741 368 2299

USA: +1407 815 2747

Skype: ***@***.***

 

From: Bob Zhang ***@***.***> 
Sent: Wednesday, 06 October 2021 00:17
To: MicrosoftDocs/powerquery-docs ***@***.***>
Cc: Gareth-Rodrigues ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/powerquery-docs] Update SumTotal.md (#161)

 

@Gareth-Rodrigues <https://github.com/Gareth-Rodrigues>  can you please take a look at the comments?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/MicrosoftDocs/powerquery-docs/pull/161#issuecomment-934931276> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AKAVG3TKHEWIGLCH5OG3XHDUFN2NHANCNFSM5COG7ZPQ> .
Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>  or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub> .   <https://github.com/notifications/beacon/AKAVG3U4M3LBDSHUXO6CXE3UFN2NHA5CNFSM5COG7ZP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOG646WTA.gif>

2021-12-20 16:00 UTC, Gareth-Rodrigues commented
Hi @bezhan-msft thanks for the heads up that this was still pending, i finally got around to updating the .md as per your feedback provided, do let me know if you see any issues with the updated changes - https://github.com/MicrosoftDocs/powerquery-docs/pull/161/files

Thanks again
Gareth

2021-12-30 00:48 UTC, bezhan-msft commented
@DougKlopfenstein can you please take a look?

2021-12-30 00:49 UTC, bezhan-msft commented on powerquery-docs/Connectors/SumTotal.md
> +| Function Reference Documentation | [Web.Contents](#https://docs.microsoft.com/en-us/powerquery-m/web-contents) <br> [Table.ToNavigationTable](https://docs.microsoft.com/en-us/power-query/helperfunc
We don't need this here as there are no new functions being created other than the main connector function.

2021-12-30 00:49 UTC, bezhan-msft commented on powerquery-docs/Connectors/SumTotal.md
> +Copy the SumTotal hosted root URL in full. This root URL is the unique URL specific to customer. The URL will be in the format of **https://\<*yourcustomerdomain*>.sumtotal.host/**. Make sure not to
to the customer

2021-12-30 00:49 UTC, bezhan-msft commented on powerquery-docs/Connectors/SumTotal.md
> +![alt text](https://marketplace.sumtotalsystems.com/Content/Product/38/media/b642fae5-f7f9-49b3-8e16-25c3cb3373ec.png)
We cannot reference external images from our docs.

2021-12-30 00:50 UTC, bezhan-msft requested changes
Left a few comments - Doug, our docs writer, might leave more.

2021-12-30 07:29 UTC, Gareth-Rodrigues commented
thank you @bezhan-msft for the reviews, i will take a look and update accordingly

2022-08-04 18:32 UTC, DougKlopfenstein commented
Closed because changes were made in private pull request that's documented above.

2022-08-04 18:32 UTC, closed without merging

2022-08-04 18:33 UTC, opbld30 commented
Docs Build status updates of commit _[b866966](https://github.com/Gareth-Rodrigues/powerquery-docs/commits/b8669662fd7ba926ad2cdc6d14fa5383290a3890)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-24e80ecd)

<a id="24e80ecd"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit b8669662fd7ba926ad2cdc6d14fa5383290a3890 in branch patch-1 of repository https://github.com/Gareth-Rodrigues/powerquery-docs into branch main (commit 4d8c295daeb359312fc60b60132fbef141ee0f3e). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0cb89e64-16a6-f377-e4a4-6c9012738630/202208041832429394-161/BuildReport?accessString=e06d7cd31f8c773ca44cefaf21624dca019eba3c967062040c83c1329cbd12d2).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0cb89e64-16a6-f377-e4a4-6c9012738630?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>