Dynamic Grouping Rules Update
MicrosoftDocs/powerquery-docs pull request #498
Opened 2024-01-04 15:11 UTC by bgribaudo

@ehrenMSFT, should the dynamic grouping rules be updated so that they mirror the edit we made to static grouping last year? 

In essence, are the rules for static and dynamic grouping identical, just performed at different points using different information (i.e. just what can be learned by static analysis vs. the additional knowledge gained from [partial] evaluation results)?

2024-01-04 16:56 UTC, Court72 commented
@DougKlopfenstein, @bezhan-msft  

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2024-01-04 20:58 UTC, ehrenMSFT commented
> @ehrenMSFT, should the dynamic grouping rules be updated so that they mirror the edit we made to static grouping last year?
> 
> In essence, are the rules for static and dynamic grouping identical, just performed at different points using different information (i.e. just what can be learned by static analysis vs. the additional knowledge gained from [partial] evaluation results)?

No, the logic is different. The static phase merges partitions based on their structure. The dynamic phase merges partitions based on what they actually access when evaluated. So two partitions that were kept separate during the static phase can end up getting merged in the dynamic phase.

2024-01-04 21:53 UTC, ehrenMSFT commented
> > @ehrenMSFT, should the dynamic grouping rules be updated so that they mirror the edit we made to static grouping last year?
> > In essence, are the rules for static and dynamic grouping identical, just performed at different points using different information (i.e. just what can be learned by static analysis vs. the additional knowledge gained from [partial] evaluation results)?
> 
> No, the logic is different. The static phase merges partitions based on their structure. The dynamic phase merges partitions based on what they actually access when evaluated. So two partitions that were kept separate during the static phase can end up getting merged in the dynamic phase.

That said, the steps you updated do seem to mirror the static phase. They just run after partitions have been trimmed using the data source info obtained during evaluation.

2024-01-22 17:07 UTC, DougKlopfenstein commented
Hi @bgribaudo - Do you have any further thoughts or changes based on Ehren's comments?

2024-01-22 23:09 UTC, bgribaudo commented
@DougKlopfenstein> Do you have any further thoughts or changes based on Ehren's comments?

@ehrenMSFT> That said, the steps you updated do seem to mirror the static phase. They just run after partitions have been trimmed using the data source info obtained during evaluation.

@ehrenMSFT, what do you think here? Should we go with this edit so that the two mirrored sets of logic are described identically?  Or would it be better to say something "partitions are merged using the same merge rules used in the static phase"?

2024-01-22 23:18 UTC, ehrenMSFT commented
> @DougKlopfenstein> Do you have any further thoughts or changes based on Ehren's comments?
> 
> @ehrenMSFT> That said, the steps you updated do seem to mirror the static phase. They just run after partitions have been trimmed using the data source info obtained during evaluation.
> 
> @ehrenMSFT, what do you think here? Should we go with this edit so that the two mirrored sets of logic are described identically? Or would it be better to say something "partitions are merged using the same merge rules used in the static phase"?

I think the latter would be good. Something like: "Partitions are then merged using the same rules described in the static grouping phase above."

2024-01-22 23:28 UTC, bgribaudo commented
Thanks, @ehrenMSFT. How does it look now?

2024-01-22 23:38 UTC, ehrenMSFT requested changes

2024-01-22 23:38 UTC, ehrenMSFT commented on powerquery-docs/data-privacy-firewall.md
> +    * Now that unnecessary partitions have been trimmed, try to create Source partitions that are as large as possible. Partitions are merged using the same rules described in the static grouping pha
```suggestion
    * Now that unnecessary partitions have been trimmed, try to create Source partitions that are as large as possible. This is done by merging the partitions using the same rules described in the static grouping phase above.
```

2024-01-23 15:48 UTC, ehrenMSFT approved these changes

2024-02-13 20:59 UTC, DougKlopfenstein commented
#sign-off

2024-02-13 21:00 UTC, DougKlopfenstein commented
@Court72 signed off, but rejected - Ehren has already signed off, so please merge.

2024-02-13 21:35 UTC, merged