adding windsor connector
MicrosoftDocs/powerquery-docs pull request #552
Opened 2024-06-20 10:16 UTC by mkzsg

2024-06-20 15:54 UTC, Court72 commented
@mkzsg - Thank you for your contribution. Would you take a moment to sign the [Contributor License Agreement (CLA)](https://github.com/MicrosoftDocs/powerquery-docs/pull/552#issuecomment-2180321883)? After the CLA is signed, someone can review your pull request. Thanks!

2024-06-20 15:54 UTC, Court72 commented
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2024-06-20 18:04 UTC, mkzsg commented
@microsoft-github-policy-service agree [company="Windsor.ai"]

2024-06-20 18:05 UTC, mkzsg commented
@microsoft-github-policy-service agree company="Windsor.ai"

2024-06-25 21:05 UTC, JasonWHowell commented
Close open to trigger a build.

2024-07-01 19:52 UTC, ptyx507x requested changes

2024-07-01 19:52 UTC, ptyx507x commented on powerquery-docs/connectors/windsor.md
> +* Data import from multiple sources
You can delete this line. You can either have Import mode and/or DIrectQuery. "Data import from multiple sources" would fall in the "Import" category

2024-07-01 19:52 UTC, ptyx507x commented
quick ping @mkzsg to please address the comments shared

2024-07-02 07:54 UTC, mkzsg commented
> quick ping @mkzsg to please address the comments shared

@ptyx507x pushed fixes. hope this is ready to go now.

2024-07-02 21:41 UTC, DougKlopfenstein commented
@mkzsg - You also need to add the Windsor connector to the list of all connectors in the Power Query documentation. The list of all connectors can be found in the connectors/index.md file. The list is in alphabetical order. Also, since your Windsor icon (windsor-64.png) is black with a transparent background, be aware that if someone is using dark mode in their web browser, your icon will disappear against the black background. If you want it to remain visible in dark mode, you should probably use a white background.

2024-07-02 22:07 UTC, DougKlopfenstein commented
@mkzsg - Also, since this is a beta release of your connector, you should add "(Beta)" to the Windsor name in the table of contents (toc.yml), the list of all connectors (connectors/index.md), and to heading 1 of the connector article.

2024-07-03 17:44 UTC, mkzsg commented
@DougKlopfenstein fixed.

2024-07-06 07:42 UTC, mkzsg commented
@DougKlopfenstein can this be merged now?

2024-07-08 20:14 UTC, DougKlopfenstein commented
@mkzsg 
I've done an edit pass to check spelling, grammar, formatting, and Microsoft style. Please take a look at the article to make sure that I didn't change the meaning of some of the more esoteric sentences. If they are OK, just leave a comment here and I'll merge the PR.

2024-07-09 06:46 UTC, mkzsg commented
> @mkzsg I've done an edit pass to check spelling, grammar, formatting, and Microsoft style. Please take a look at the article to make sure that I didn't change the meaning of some of the more esoteric sentences. If they are OK, just leave a comment here and I'll merge the PR.

Yes, all OK. LGTM. Let's merge.

2024-07-09 14:03 UTC, DougKlopfenstein approved these changes

2024-07-09 19:19 UTC, JasonWHowell commented
@Court72 can you review sometime today? Thanks, Jason

2024-07-09 20:44 UTC, Jak-MS commented
@DougKlopfenstein @JasonWHowell - usually PR review would prefer to move the commits for new articles to the private repo. Getting a staged page ensures that (among other things) images display correctly and Acrolinx helps us check for editorial issues like unapproved acronyms, typos, and spelling errors. That said, we'll merge this with the following recommendation:

@mkzsg - can you check the article after it goes live to ensure all the images display correctly and the page renders as you intended? thanks!

2024-07-09 20:44 UTC, merged